name: Build and Release to MavenLocal

on:
  workflow_call:
    inputs:
      input-cache-prefix:
        description: 'Input cache prefix'
        type: string
        required: false
        default: ''
      output-cache-prefix:
        description: 'Output cache prefix'
        type: string
        required: false
        default: ''
      release-build-command:
        description: 'Release build command'
        type: string
        required: true
      publish-to-maven-local-command:
        description: 'Publish to MavenLocal command'
        type: string
        required: true

jobs:
  publish:
    name: Publish plugins to MavenLocal
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11

      - name: Setup secrets
        run: bash ./.github/scripts/setup_secrets.sh "${{ secrets.GOOGLE_CLIENT_ID}}" "${{ secrets.FACEBOOK_APP_ID }}" "${{ secrets.FACEBOOK_CLIENT_TOKEN }}" "${{ secrets.MICROSOFT_CLIENT_ID }}" "${{ secrets.MICROSOFT_SIGNATURE_HASH }}" "${{ secrets.DROPBOX_APP_KEY }}"

      - name: Set useMavenLocal flag
        run: echo useMavenLocal=true >> local.properties

      - name: Restore MavenLocal Cache
        if: ${{ inputs.input-cache-prefix != '' }}
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ inputs.input-cache-prefix }}-${{ github.run_id }}

      - name: Release build
        run: ./gradlew ${{ inputs.release-build-command }}
      - name: Source jar
        run: ./gradlew androidSourcesJar

      - name: Publish to MavenLocal
        run: ./gradlew ${{ inputs.publish-to-maven-local-command }}

      - name: Cache MavenLocal
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ inputs.output-cache-prefix }}-${{ github.run_id }}
