name: Android CI

on:
  pull_request:
    branches: [ master, main, develop ]
    types: [ opened, synchronize ]

jobs:
  assemble_modules:
    name: Assemble modules
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Update local properties for secrets
        run: |
          echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> ./local.properties &&
          echo FACEBOOK_APP_ID=${{ secrets.FACEBOOK_APP_ID }} >> ./local.properties &&
          echo FACEBOOK_CLIENT_TOKEN=${{ secrets.FACEBOOK_CLIENT_TOKEN }} >> ./local.properties &&
          echo MICROSOFT_CLIENT_ID=${{ secrets.MICROSOFT_CLIENT_ID }} >> ./local.properties &&
          echo KEYSTORE_HASH=${{ secrets.KEYSTORE_HASH }} >> ./local.properties

      - name: Set useMavenLocal flag
        run: echo useMavenLocal=true >> local.properties

      - name: Publish Core to MavenLocal
        run: ./gradlew :packages:core:publishToMavenLocal

      - name: Publish Plugins to MavenLocal
        run: ./gradlew publishToMavenLocal

      - name: Assemble app debug APK
        run: ./gradlew assembleDebug

  code_quality_analysis:
    name: Check code quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Update local properties for secrets
        run: |
          echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> ./local.properties &&
          echo FACEBOOK_APP_ID=${{ secrets.FACEBOOK_APP_ID }} >> ./local.properties &&
          echo FACEBOOK_CLIENT_TOKEN=${{ secrets.FACEBOOK_CLIENT_TOKEN }} >> ./local.properties &&
          echo MICROSOFT_CLIENT_ID=${{ secrets.MICROSOFT_CLIENT_ID }} >> ./local.properties &&
          echo KEYSTORE_HASH=${{ secrets.KEYSTORE_HASH }} >> ./local.properties

      - name: Set useMavenLocal flag
        run: echo useMavenLocal=true >> local.properties

      - name: Publish Core to MavenLocal
        run: ./gradlew :packages:core:publishToMavenLocal

      - name: Publish Plugins to MavenLocal
        run: ./gradlew publishToMavenLocal

      - name: Misspelling on detekt + ktlint
        run: ./gradlew detekt --stacktrace --continue

      - name: Run unit tests and check coverage
        run: ./gradlew jacocoCoverageVerification --stacktrace --continue
