name: Publish Microsoft Plugin

on:
  workflow_dispatch:
    inputs:
      destination-repository:
        type: choice
        required: true
        description: Destination repository
        options:
          - snapshot
          - release

jobs:
  publish:
    name: Publish Microsoft Plugin
    uses: ./.github/workflows/build_and_publish_to_maven_remotely.yml
    with:
      package-name: :packages:plugin-microsoft
      destination-repository: ${{ github.event.inputs.destination-repository }}
    secrets: inherit
