name: Publish Core Package

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish Core Package
    uses: ./.github/workflows/build_and_publish_to_maven_remotely.yml
    with:
      package-name: :packages:core
    secrets: inherit
